% HOWTO NO. 5: Plotting in GrafLab and the output variable
%
% All the GrafLab input parameters are explained in "../doc/graflab.md".


clear;
clc;
howto = 5;
intro(howto, "PLOTTING IN GRAFLAB AND THE OUTPUT VARIABLE", ...
      "This HOWTO shows outputs from GrafLab, focusing on plotting " + ...
      "and the output variable ""out"".");






% Plotting with "Mapping Toolbox"
% =============================================================================

fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Plotting with the Mapping Toolbox\n");
fprintf("-----------------------------------------\n");
fprintf("\n");
fprintf("The plots are nice, but the plotting may be " + ...
        "very slow for large grids.\n");
fprintf("\n");


GM                = 3986004.415E+8;
R                 = 6378136.3;
nmin              = 0;
nmax              = 360;
ellipsoid         = 1;  % GRS80
GGM_path          = '../data/input/EGM96.mat';
crd               = 0;  % Evaluation points are defined in ellipsoidal 
                        % coordinates
point_type        = 0;  % Computation at a grid
lat_grd_min       = -90.0;
lat_grd_step      =   1.0;
lat_grd_max       =  90.0;
lon_grd_min       =   0.0;
lon_grd_step      = lat_grd_step;
lon_grd_max       = 360.0;
h_grd             =   0.0;
out_path          = '../data/output/howto05-mapping-toolbox';
quantity_or_error = 0;
quantity          = [5];  % Disturbing potential
fnALFs            = 1;
export_data_txt   = 1;
export_report     = 1;
export_data_mat   = 1;
display_data      = 1;
graphic_format    = 6;
colormap          = 1;
number_of_colors  = 60;
dpi               = 300;
status_bar        = 1;


% Do the synthesis
tic
out_mt = GrafLab('OK', ...
    GM, ...
    R, ...
    nmin, ...
    nmax, ...
    ellipsoid, ...
    GGM_path, ...
    crd, ...
    point_type, ...
    lat_grd_min, ...
    lat_grd_step, ...
    lat_grd_max, ...
    lon_grd_min, ...
    lon_grd_step, ...
    lon_grd_max, ...
    h_grd, ...
    [], ...
    [], ...
    [], ...
    [], ...
    out_path, ...
    quantity_or_error, ...
    quantity, ...
    fnALFs, ...
    [], ...
    export_data_txt, ...
    export_report, ...
    export_data_mat, ...
    display_data, ...
    graphic_format, ...
    colormap, ...
    number_of_colors, ...
    dpi, ...
    status_bar);
time_mt = toc;


fprintf("\n");
fprintf("You may now check the ""%s*.png"" file " + ...
        "with the plot.\n", out_path);
fprintf("%0.1f sec were needed to do the synthesis and plot the " + ...
        "results.\n", time_mt);

% =============================================================================






% Plotting with the "imagesc" function
% =============================================================================

fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Plotting with the ""imagesc"" function\n");
fprintf("-----------------------------------------\n");
fprintf("\n");
fprintf("Very simple plots, but also very fast plotting, even with " + ...
        "large grids.\n");
fprintf("\n");

display_data = 2;
out_path     = '../data/output/howto05-imagesc';


fprintf("\n");


% Do the synthesis
tic;
out_imgsc = GrafLab('OK', ...
    GM, ...
    R, ...
    nmin, ...
    nmax, ...
    ellipsoid, ...
    GGM_path, ...
    crd, ...
    point_type, ...
    lat_grd_min, ...
    lat_grd_step, ...
    lat_grd_max, ...
    lon_grd_min, ...
    lon_grd_step, ...
    lon_grd_max, ...
    h_grd, ...
    [], ...
    [], ...
    [], ...
    [], ...
    out_path, ...
    quantity_or_error, ...
    quantity, ...
    fnALFs, ...
    [], ...
    export_data_txt, ...
    export_report, ...
    export_data_mat, ...
    display_data, ...
    graphic_format, ...
    colormap, ...
    number_of_colors, ...
    dpi, ...
    status_bar);
time_imagsc = toc;


fprintf("\n");
fprintf("You may now check the ""%s*.png"" file " + ...
        "with the plot.\n", out_path);
fprintf("%0.1f sec were needed to do the synthesis and plot the " + ...
        "results.\n", time_imagsc);
fprintf("\n");

% =============================================================================






% Output variable from GrafLab
% =============================================================================

fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Output variable from GrafLab\n");
fprintf("-----------------------------------------\n");
fprintf("\n");
fprintf("You may redirect the numerical outputs from GrafLab to a " + ...
        "MATLAB variable.  The output variable then contains the " + ...
        "numerical data that GrafLab uses to prepare the ""txt"" and/or " + ...
        """mat"" file(s).  Note that the ""out_path"" must be " + ...
        "specified, even if you do not export any data or plot.\n");
fprintf("In this HOWTO, the GrafLab numerical outputs are saved in " + ...
        """out_mt"" and ""out_imgsc"" variables.  You may explore these " + ...
        "variables now.\n");
fprintf("\n");

% =============================================================================






outro(howto);
