% HOWTO NO. 2: Minimum and maximum harmonic degree of the synthesis
%
% All the GrafLab input parameters are explained in "../doc/graflab.md".


clear;
clc;
howto = 3;
intro(howto, "MINIMUM AND MAXIMUM HARMONIC DEGREE OF THE SYNTHESIS", ...
      "This HOWTO demonstrates a modification of the minimum and the " + ...
      "maximum harmonic degree of the synthesis.");






% Synthesis up to degree 10
% =============================================================================

GM                = 3986004.415E+8;
R                 = 6378136.3;
nmin              = 0;
nmax              = 10;
ellipsoid         = 1;  % GRS80
GGM_path          = '../data/input/EGM96.mat';
crd               = 0;  % Evaluation points are defined in ellipsoidal 
                        % coordinates
point_type        = 0;  % Computation at a grid
lat_grd_min       = -90.0;
lat_grd_step      =   1.0;
lat_grd_max       =  90.0;
lon_grd_min       =   0.0;
lon_grd_step      =   1.0;
lon_grd_max       = 360.0;
h_grd             =   0.0;
out_path          = sprintf('../data/output/howto02-nmin%d-nmax%d', ...
                            nmin, nmax);
quantity_or_error = 0;
quantity          = [5];  % Disturbing potential
fnALFs            = 1;
export_data_txt   = 1;
export_report     = 1;
export_data_mat   = 1;
display_data      = 0;
status_bar        = 1;


fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Synthesis from nmin = %d up to nmax = %d\n", nmin, nmax);
fprintf("-----------------------------------------\n");
fprintf("\n");


% Do the synthesis
out_grd = GrafLab('OK', ...
    GM, ...
    R, ...
    nmin, ...
    nmax, ...
    ellipsoid, ...
    GGM_path, ...
    crd, ...
    point_type, ...
    lat_grd_min, ...
    lat_grd_step, ...
    lat_grd_max, ...
    lon_grd_min, ...
    lon_grd_step, ...
    lon_grd_max, ...
    h_grd, ...
    [], ...
    [], ...
    [], ...
    [], ...
    out_path, ...
    quantity_or_error, ...
    quantity, ...
    fnALFs, ...
    [], ...
    export_data_txt, ...
    export_report, ...
    export_data_mat, ...
    display_data, ...
    [], ...
    [], ...
    [], ...
    [], ...
    status_bar);

% =============================================================================






% Synthesis up to the maximum degree of a GGM
% =============================================================================

fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Synthesis from nmin = %d up to the maximum harmonic degree " + ...
        "found in ""%s""\n", nmin, GGM_path);
fprintf("-----------------------------------------\n");
fprintf("\n");
fprintf("The maximum harmonic degree in ""%s"" is 360.  " + ...
        "To do the synthesis up to this degree, you may manually " + ...
        "set the ""nmax"" value to ""360"" or, even better, to " + ...
        "'nmaxGGM'.  In the latter case, GrafLab scans the file for its " + ...
        "maximum harmonic degree and automatically uses the " + ...
        "maximum value it founds.  This is useful when dealing " + ...
        "with multiple GGM files with varying maximum harmonic " + ...
        "degree, e.g., monthly gravity field solutions.\n", GGM_path);
fprintf("\n");


nmax     = 'nmaxGGM';
out_path = sprintf('../data/output/howto02-nmin%d-nmaxGGM', nmin);


% Do the synthesis
out_grd = GrafLab('OK', ...
    GM, ...
    R, ...
    nmin, ...
    nmax, ...
    ellipsoid, ...
    GGM_path, ...
    crd, ...
    point_type, ...
    lat_grd_min, ...
    lat_grd_step, ...
    lat_grd_max, ...
    lon_grd_min, ...
    lon_grd_step, ...
    lon_grd_max, ...
    h_grd, ...
    [], ...
    [], ...
    [], ...
    [], ...
    out_path, ...
    quantity_or_error, ...
    quantity, ...
    fnALFs, ...
    [], ...
    export_data_txt, ...
    export_report, ...
    export_data_mat, ...
    display_data, ...
    [], ...
    [], ...
    [], ...
    [], ...
    status_bar);


fprintf("\n");

% =============================================================================






% Synthesis up to maximum degree smaller than 2
% =============================================================================

% GrafLab refuses to do a synthesis up to maximum degree that is smaller than 
% "2".  This is due to some unwise decisions made in the early months of the 
% GrafLab development.  Hopefully, this will be fixed one day.  Until then, if 
% you need "nmax" smaller than "2", there is a workaround,
%
%     1) prepare a GGM file with coefficients up to degree at least "2",
%
%     2) set all coefficients beyond your "nmax" (which is either "0" or "1") 
%        to zero, and
%
%     3) do the synthesis at least up to "nmax = 2".
%
% If is *not* recommended to do this kind of a trick
%
%     1) for any quantity that involves the normal gravity field (the
%        coefficient "C20_ell" of the normal field would be incorrectly 
%        subtracted), and
%
%     2) for the gravitational and distubring tensor in the local 
%        north-oriented reference frame.

% =============================================================================






% Synthesis from "nmin" larger than zero
% =============================================================================

nmin     = 5;  % Increase the minimum degree of the synthesis
quantity = [5];
out_path = sprintf('../data/output/howto02-nmin%d-nmaxGGM', nmin);


fprintf("\n\n\n\n");
fprintf("-----------------------------------------\n");
fprintf("Synthesis from nmin = %d up to the maximum harmonic degree " + ...
        "found in ""%s""\n", nmin, GGM_path);
fprintf("-----------------------------------------\n");
fprintf("\n");
fprintf("In addition to modifying ""nmax"", you may also change " + ...
        "the ""nmin"" value.  ""nmin"" represents the minimum degree " + ...
        "of the harmonic synthesis.  For some gravity field " + ...
        "quantities, however, GrafLab does not allow non-zero " + ...
        """nmin"" value.  The quantities includes: 9, 10, 15, 20, 23 " + ...
        "(see the code numbers for ""quantity"" from " + ...
        """../doc/graflab.md"").  If you attempt to evaluate these " + ...
        "quantities with ""nmin > 0"", you will get an error.  If you " + ...
        "set ""nmin"" to a value larger than ""nmax"", you will get an " + ...
        "error, too.\n");
fprintf("\n");


% Do the synthesis
out_grd = GrafLab('OK', ...
    GM, ...
    R, ...
    nmin, ...
    nmax, ...
    ellipsoid, ...
    GGM_path, ...
    crd, ...
    point_type, ...
    lat_grd_min, ...
    lat_grd_step, ...
    lat_grd_max, ...
    lon_grd_min, ...
    lon_grd_step, ...
    lon_grd_max, ...
    h_grd, ...
    [], ...
    [], ...
    [], ...
    [], ...
    out_path, ...
    quantity_or_error, ...
    quantity, ...
    fnALFs, ...
    [], ...
    export_data_txt, ...
    export_report, ...
    export_data_mat, ...
    display_data, ...
    [], ...
    [], ...
    [], ...
    [], ...
    status_bar);


fprintf("\n");

% =============================================================================






outro(howto);
